..
  Supported languages https://pygments.org/docs/lexers/
  Sections https://devguide.python.org/documenting/#sections

  #####################
  Title of the Document
  #####################

  ****************
  Title of chapter
  ****************

  Level 1 Sections
  ################

  Level 2 Sections
  ****************

  Level 3 Section
  ===============

  Level 4 Section
  ---------------

  Level 5 Section
  ^^^^^^^^^^^^^^^

  Level 6 Section
  """""""""""""""

##########
References
##########

- Clean Architecture

  - `Implementing Clean Architecture with Quarkus`_

    - `lievendoclo/clean-arch-quarkus`_

  - `Clean Architecture Guide (with tested examples)`_
  - `Clean Architecture For The Rest Of Us`_
  - `Clean Architecture Example with Java and Spring Boot`_

- Quarkus_

  - `Quarkus - Get Started`_
  - `Quarkus Workshop`_

- Identities

  - `ID properties on Domain objects in DDD`_
  - `PolyglotPersistence`_

- Value Objects

  - `Don’t use Lombok`_
  - `Immutables`_

.. Links

.. _Quarkus: https://quarkus.io/
.. _`Quarkus - Get Started`: https://quarkus.io/get-started/
.. _`Quarkus Workshop`: https://quarkus.io/quarkus-workshops/super-heroes/
.. _`Implementing Clean Architecture with Quarkus`: https://blog.sourced-bvba.be/article/2020/03/11/ca-quarkus/
.. _`lievendoclo/clean-arch-quarkus`: https://github.com/lievendoclo/clean-arch-quarkus
.. _`Clean Architecture Guide (with tested examples)`: https://proandroiddev.com/clean-architecture-data-flow-dependency-rule-615ffdd79e29
.. _`Clean Architecture For The Rest Of Us`: https://pusher.com/tutorials/clean-architecture-introduction
.. _`Clean Architecture Example with Java and Spring Boot`: https://medium.com/swlh/clean-architecture-java-spring-fea51e26e00
.. _`ID properties on Domain objects in DDD`: https://softwareengineering.stackexchange.com/a/299668
.. _`PolyglotPersistence`: https://martinfowler.com/bliki/PolyglotPersistence.html
.. _`Don’t use Lombok`: https://medium.com/@vgonzalo/dont-use-lombok-672418daa819
.. _`Immutables`: https://immutables.github.io/
